### ISSUE TITLE
How i should reshape?

### ISSUE THREAD

**Issue by FireFox1616** [ariskag/vLSH#2]
I'm trying yo implement vlsh with the California ND Datastet, wich is composed by 701 photos. 10 subject wrote down in a txt file which photos are near duplicate for them , and we have also correlation matrix. I don't know what i'm doing wrong because the content of the buckets and the width are very very wrong. I think that the porblem is how i do the reshape: The images are RGB and i reduced them in 20x20. I created a 4-d array 20x20x3x701.  So i tried to reshape and obtained a 1200x701  matrix, but the problem is that reshape can't maintain the order of the original matrix. I can post the matlab code:

> 

`path='C:\Users\franc\Desktop\stage\californiaND\prova\*.jpg';
path2='C:\Users\franc\Desktop\stage\californiaND\prova\';

d=dir(path);
a=[];
for m=1:length(d)
 a=cat(4,a,imread(strcat(path2,d(m).name)));
end
r=reshape(a,[],701);
r=double(r);
L = lshConstruct( r, 10,4);`
>
so, the problem is how i do correctly the reshape? I need to transform a 4d array into a 2d one mainting order or i am doing something else wrong? Thank you

**Comment by ariskag** [comment]
Hi, and sorry for my late response.

I also feel that this reshape method would not fit the purpose. Vectors contain R & G & B values, therefore any hash collision would be expected to be the result of vectors with color similarity in the same pixels. But still, this is not true since this color vector holds no information of the spatial distribution of the color values in the 2D image. And the fact that we are not dealing with a grey-scale but with 3 colors makes our case even more complex.

We need to produce a vector that can somehow contain useful information, which would be the content of the image itself (shapes, lines, contrast, I guess). The **Scale-Invariant Feature Transform** was developed in this purpose (paper "_Distinctive image features from scale-invariant keypoints_" by _David Lowe_).

There is a demo software available in _http://www.cs.ubc.ca/~lowe/keypoints/_ for extracting SIFT descriptors from a PGM image, containing matlab scripts. I don't know if this can be of any help, I've never used it until now just to check its output. After converting  JPEG to PGM (grey-scale format) 'sift.m' script gives me ~650 descriptors (number of descriptors varied between images), each being a 128-length vector. I haven't checked further how one can use these descriptors in order to produce a single vector.

There should be Matlab computer vision algorithms that could be helpful. From a quick search I discovered _https://www.mathworks.com/help/vision/feature-detection-and-extraction.html_, maybe it could be helpful (I haven't read the documentation of the functions listed there yet, I want to check it). There it contains also the SURF feature detection algorithm, which is similar to SIFT.

Apart from the vector representation stuff, I'd like to add that value M=4 might be a relatively small number of LSH projection dimensions. In my experiments with the SIFT1M dataset (_http://corpus-texmex.irisa.fr/_) I remember I was using 10+ with good results, but this of course is varying depending on the dataset and the other LSH parameter values used.

Your issue about generating a vector representing an image is interesting. When vLSH was being developed, the code had always been tested with already available datasets of vectors, not requiring any pre-processing.

I hope I was of some help, at least regarding the concept behind the creation of the vectors, since I don't have any ready solution for this right now. If you have any updates or thoughts on this issue please share them. I'll also try and check this further, if I come up with a suitable concept or anything that could be of any help I'll let you know.

**Comment by FireFox1616** [comment]
Thank you for the answer! I will try to use sift descriptors and feature detection, maybe it will help. If i'll come up with some solution i will let you know. Thank you again
